import nextConfig from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';
import prettierConfig from 'eslint-config-prettier';

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      '.next/**/*',
      'node_modules/**',
      'out/**',
      'build/**',
      'dist/**',
      '.vercel/**',
      'public/**',
      '*.config.js',
      '*.config.ts',
      '*.config.mjs',
      'eslint-rules/**',
      // Reference prototypes, not application source — they are the design
      // brief's own code and are read, not built.
      'docs/**',
      'next-env.d.ts',
      // Payload generates these — they're regenerated by `pnpm generate:types`,
      // `pnpm generate:importmap`, and `pnpm db:migrate:create`, so linting
      // them just creates churn we can't fix at the source.
      'src/payload-types.ts',
      'src/migrations/**',
      'src/app/(payload)/admin/importMap.js',
    ],
  },
  ...nextConfig,
  ...nextTypescript,
  {
    settings: {
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
        },
      },
    },
  },
  {
    rules: {
      // Disable new react-hooks v7 rules until pre-existing patterns are refactored
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/refs': 'off',
    },
  },
  prettierConfig,
];

export default eslintConfig;
