/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    trails: Trail;
    'trail-conditions': TrailCondition;
    'trail-areas': TrailArea;
    'trail-ratings': TrailRating;
    'trail-kinds': TrailKind;
    'trail-condition-types': TrailConditionType;
    organizations: Organization;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    trails: TrailsSelect<false> | TrailsSelect<true>;
    'trail-conditions': TrailConditionsSelect<false> | TrailConditionsSelect<true>;
    'trail-areas': TrailAreasSelect<false> | TrailAreasSelect<true>;
    'trail-ratings': TrailRatingsSelect<false> | TrailRatingsSelect<true>;
    'trail-kinds': TrailKindsSelect<false> | TrailKindsSelect<true>;
    'trail-condition-types': TrailConditionTypesSelect<false> | TrailConditionTypesSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'condition-reporting': ConditionReporting;
    'map-appearance': MapAppearance;
    theme: Theme;
  };
  globalsSelect: {
    'condition-reporting': ConditionReportingSelect<false> | ConditionReportingSelect<true>;
    'map-appearance': MapAppearanceSelect<false> | MapAppearanceSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trails".
 */
export interface Trail {
  id: number;
  /**
   * The name everything else follows from. It is also the raw `Trail` value from the Mapbox tileset and the join key to rendered features — so on an existing trail, change it only if the upstream GIS data changed.
   */
  trailName: string;
  city: 'chattanooga' | 'bend';
  /**
   * Manage the list under Lists → Trail complexes.
   */
  area: number | TrailArea;
  /**
   * Who looks after this trail. Manage the list under Lists → Stewards.
   */
  organization?: (number | null) | Organization;
  /**
   * Manage the list under Lists → Trail ratings.
   */
  rating: number | TrailRating;
  /**
   * Drives the line colour and sidebar icon, both of which come from the kind and rating rows rather than being stored per trail. Manage the list under Lists → Trail kinds.
   */
  kind: number | TrailKind;
  /**
   * Stops new condition reports for this trail. Existing reports stay visible.
   */
  conditionReportsClosed?: boolean | null;
  /**
   * Optional, e.g. “Closed for logging until 1 May.” Shown in place of the Report button.
   */
  conditionReportsNote?: string | null;
  /**
   * The name riders see in the sidebar and the elevation pane.
   */
  displayName: string;
  /**
   * Identifies the trail in URLs and names its elevation profile. Changing it on an existing trail moves where that profile is looked up.
   */
  slug: string;
  geom?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  osmIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Re-derive on the next save even if nothing changed. For an OSM trail that refetches the ways; for an edited one it just re-measures the line.
   */
  rebuildGeometry?: boolean | null;
  osmReport?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Miles, measured from the OSM geometry.
   */
  distance?: number | null;
  /**
   * Feet, sampled from Mapbox Terrain-RGB.
   */
  elevationGain?: number | null;
  elevationLoss?: number | null;
  elevationMin?: number | null;
  elevationMax?: number | null;
  /**
   * [swLng, swLat, neLng, neLat], for zoom-to-fit.
   */
  bounds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The per-point elevation chart, sampled on save. Trails in the checked-in data are served from public/data/elevation instead; this is what a trail created here draws from.
   */
  elevationProfile?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * OSM trails rebuild their line from the picked ways on every save. Edited trails keep the line as drawn — the map sets this for you the first time you move a point. Imported trails are left alone entirely.
   */
  geometrySource: 'osm' | 'edited' | 'imported';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Trail complexes trails are grouped under, and the region each sits in. Anything added here becomes selectable on a trail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-areas".
 */
export interface TrailArea {
  id: number;
  /**
   * As shown in the sidebar, e.g. "Phil's Trail Complex".
   */
  name: string;
  city: 'chattanooga' | 'bend';
  /**
   * The heading this complex sits under in the sidebar — the level above it, e.g. "Bend" or "Cascade Lakes". Leave blank to use the built-in mapping.
   */
  region?: string | null;
  /**
   * Optional.
   */
  description?: string | null;
  /**
   * Stops new condition reports for every trail in this complex. Existing reports stay visible.
   */
  conditionReportsClosed?: boolean | null;
  /**
   * Optional, e.g. “Whole complex shut for the wet season.” Shown in place of the Report button.
   */
  conditionReportsNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The clubs and agencies that look after trails — volunteer groups and land managers alike. Anything added here becomes selectable on a trail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  /**
   * Full name, e.g. "Central Oregon Trail Alliance".
   */
  name: string;
  /**
   * e.g. "COTA". Shown where space is tight.
   */
  abbreviation?: string | null;
  city?: ('chattanooga' | 'bend') | null;
  /**
   * Where riders can find them — membership, trail reports.
   */
  url?: string | null;
  /**
   * A sentence or two. Optional.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * How trails are graded, and the colour each grade draws in. Anything added here becomes selectable on a trail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-ratings".
 */
export interface TrailRating {
  id: number;
  /**
   * As shown in the admin, e.g. "Intermediate".
   */
  name: string;
  /**
   * The stable key the map and sidebar match on, e.g. "intermediate". Lowercase and dashes.
   */
  value: string;
  /**
   * The colour trails with this rating draw in.
   */
  color: string;
  /**
   * Low to high, easiest first. Orders this list and the dropdown on a trail.
   */
  sortOrder: number;
  /**
   * What this grade means locally. Optional.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The sorts of trail on the map, and how each is drawn. Anything added here becomes selectable on a trail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-kinds".
 */
export interface TrailKind {
  id: number;
  /**
   * As shown in the admin, e.g. "Greenway".
   */
  name: string;
  /**
   * The stable key the map matches on, e.g. "greenway". Lowercase and dashes.
   */
  value: string;
  /**
   * Marks trails of this kind in the sidebar.
   */
  icon: 'mountain' | 'route';
  /**
   * Optional. Overrides the rating colour — leave blank to let difficulty decide.
   */
  color?: string | null;
  /**
   * Optional.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * What riders have reported. These are live on the map as soon as they arrive — tick “Hidden” to take one down.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-conditions".
 */
export interface TrailCondition {
  id: number;
  trail: number | Trail;
  condition: number | TrailConditionType;
  /**
   * When it was ridden, not when this was typed.
   */
  observedAt: string;
  /**
   * Official means the steward said so, not a rider.
   */
  source: 'public' | 'admin';
  /**
   * Takes this off the public map. The row stays, so repeat abuse is still visible here.
   */
  hidden?: boolean | null;
  city: 'chattanooga' | 'bend';
  /**
   * A one-way hash of the submitter’s IP, so repeat abuse can be found together. The address itself is never stored.
   */
  reporterHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * What riders can report a trail as being. Anything added here becomes selectable on the report form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-condition-types".
 */
export interface TrailConditionType {
  id: number;
  /**
   * As riders see it, e.g. "Muddy — stay off".
   */
  name: string;
  /**
   * The stable key the map matches on, e.g. "muddy". Lowercase and dashes.
   */
  value: string;
  /**
   * The badge colour.
   */
  color: string;
  /**
   * Low to high, best first. Orders the dropdown.
   */
  sortOrder: number;
  /**
   * Untick to retire an option. Deleting one that past reports use is blocked.
   */
  active?: boolean | null;
  /**
   * Draws the trail as a red dashed line, and the badge stops expiring — a closure holds until someone reports something else. Nothing to do with the “closed to new reports” switches on a trail.
   */
  marksClosed?: boolean | null;
  /**
   * What this means locally. Optional.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Who can sign in and edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * One role for now. Adding another here is what turns the access rules across the collections into a real distinction.
   */
  role: 'admin';
  /**
   * Which city this user can change. Ignored for admins, who can edit every city.
   */
  city?: ('chattanooga' | 'bend') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'trails';
        value: number | Trail;
      } | null)
    | ({
        relationTo: 'trail-conditions';
        value: number | TrailCondition;
      } | null)
    | ({
        relationTo: 'trail-areas';
        value: number | TrailArea;
      } | null)
    | ({
        relationTo: 'trail-ratings';
        value: number | TrailRating;
      } | null)
    | ({
        relationTo: 'trail-kinds';
        value: number | TrailKind;
      } | null)
    | ({
        relationTo: 'trail-condition-types';
        value: number | TrailConditionType;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trails_select".
 */
export interface TrailsSelect<T extends boolean = true> {
  trailName?: T;
  city?: T;
  area?: T;
  organization?: T;
  rating?: T;
  kind?: T;
  conditionReportsClosed?: T;
  conditionReportsNote?: T;
  displayName?: T;
  slug?: T;
  geom?: T;
  osmIds?: T;
  rebuildGeometry?: T;
  osmReport?: T;
  distance?: T;
  elevationGain?: T;
  elevationLoss?: T;
  elevationMin?: T;
  elevationMax?: T;
  bounds?: T;
  elevationProfile?: T;
  geometrySource?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-conditions_select".
 */
export interface TrailConditionsSelect<T extends boolean = true> {
  trail?: T;
  condition?: T;
  observedAt?: T;
  source?: T;
  hidden?: T;
  city?: T;
  reporterHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-areas_select".
 */
export interface TrailAreasSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  region?: T;
  description?: T;
  conditionReportsClosed?: T;
  conditionReportsNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-ratings_select".
 */
export interface TrailRatingsSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  color?: T;
  sortOrder?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-kinds_select".
 */
export interface TrailKindsSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  icon?: T;
  color?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trail-condition-types_select".
 */
export interface TrailConditionTypesSelect<T extends boolean = true> {
  name?: T;
  value?: T;
  color?: T;
  sortOrder?: T;
  active?: T;
  marksClosed?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  abbreviation?: T;
  city?: T;
  url?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Whether riders can report trail conditions. Turning this off leaves existing reports visible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "condition-reporting".
 */
export interface ConditionReporting {
  id: number;
  /**
   * Untick to close the report form across the whole map.
   */
  enabled?: boolean | null;
  /**
   * Optional, e.g. “Conditions are reported on our forum instead.”
   */
  disabledMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The colours riders see. Trail and condition colours live under Lists — these are the interface itself.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-appearance".
 */
export interface MapAppearance {
  id: number;
  /**
   * Selected trails, focus rings, the main button. Used sparingly — leave blank for the default.
   */
  primaryColor?: string | null;
  /**
   * Headings and body text across the map interface. Needs to stay readable on white.
   */
  secondaryColor?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * How the admin looks. Changes apply on the next page load. Clear a field to fall back to the default.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Focus rings and highlights. Default #c3f44d.
   */
  accentColor?: string | null;
  /**
   * Deep brand colour. Default #1a434e.
   */
  deepColor?: string | null;
  /**
   * The cast of the greys everything is built from. Applies to both light and dark mode, because Payload derives dark mode by inverting the same scale.
   */
  neutralTint?: ('cool' | 'neutral' | 'warm') | null;
  cornerStyle?: ('sharp' | 'soft' | 'round') | null;
  fontFamily?: ('geist' | 'system' | 'serif') | null;
  /**
   * Escape hatch for anything the fields above do not cover. Injected verbatim into the admin. Admins only — treat it as code.
   */
  customCss?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "condition-reporting_select".
 */
export interface ConditionReportingSelect<T extends boolean = true> {
  enabled?: T;
  disabledMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "map-appearance_select".
 */
export interface MapAppearanceSelect<T extends boolean = true> {
  primaryColor?: T;
  secondaryColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  accentColor?: T;
  deepColor?: T;
  neutralTint?: T;
  cornerStyle?: T;
  fontFamily?: T;
  customCss?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}